module.exports = {
  ROLES: {
    ADMIN: "ADMIN",
    TEACHER: "TEACHER",
    ACCOUNTANT: "ACCOUNTANT",
    PARENT: "PARENT",
    TRANSPORT_MANAGER: "TRANSPORT_MANAGER"
  },
  FEATURE_FLAGS: {
    AI_ASSISTANT: "AI_ASSISTANT",
    AI_INSIGHTS: "AI_INSIGHTS",
    AI_FEES_PREDICT: "AI_FEES_PREDICT",
    AI_OCR: "AI_OCR",
    AI_REPORTS: "AI_REPORTS",
    AI_TIMETABLE: "AI_TIMETABLE",
    AI_MESSAGING: "AI_MESSAGING",
    NOTIFICATIONS: "NOTIFICATIONS"
  }
};
